### ISSUE TITLE
`inject` is not supported in `integratedTerminal`.

### ISSUE THREAD

**Issue by yosoymin** [actboy168/lua-debug#180]
Since version 1.58.0 I can't debug lua, when I click on play button I can see the next error:

![image](https://user-images.githubusercontent.com/3405275/171396343-f59ab5b7-1e13-48cd-81f8-ccddf91b18ac.png)

**Comment by stax76** [comment]
@yosoymin 

Does v1.58.1 work for you? For me, it does not show this message, but it doesn't break at breakpoints.

@actboy168 

Unless I'm missed something, there is still an issue.

**Comment by actboy168** [comment]
@stax76  My fault. It should work now.

**Comment by yosoymin** [comment]
> @yosoymin
> 
> Does v1.58.1 work for you? For me, it does not show this message, but it doesn't break at breakpoints.
> 
> @actboy168
> 
> Unless I'm missed something, there is still an issue.

You are right, it's not showing the message but breakpoints are not working. It seems the debugger is not connecting the application, I can't stop the application either using the stop button.

**Comment by stax76** [comment]
The issue is still present in v1.58.2. It does not show the error message, but does not break at the breakpoint.

**Comment by actboy168** [comment]
@stax76 You may have set the console in settings. Reset it or change it to internalConsole.

**Comment by stax76** [comment]
>  You may have set the console in settings. Reset it or change it to internalConsole.

That was the problem, I changed it to `internalConsole`, and now it works, thank you!

**Comment by yosoymin** [comment]
> @stax76 You may have set the console in settings. Reset it or change it to internalConsole.

Ok, setting the `console` setting to `internalConsole` is working for me too. I think we can close this issue!
